name: 'Apply latest configuration to Fleet'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # allows manual triggering
  schedule:
  - cron: '0 6 * * *' # Nightly 6AM UTC

# Prevent concurrent runs of this workflow.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

# Limit permissions of GITHUB_TOKEN.
permissions:
  contents: read

jobs:
  fleet-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1Password
        id: op-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          FLEET_URL: op://GitHub/FLEET_URL
          FLEET_API_TOKEN: op://GitHub/FLEET_API_TOKEN
          GLOBAL_ENROLL_SECRET: op://GitHub/GLOBAL_ENROLL_SECRET
          SSO_METADATA_URL: op://GitHub/SSO_METADATA_URL
          FLEET_SERVERS_ENROLL_SECRET: op://GitHub/FLEET_SERVERS_ENROLL_SECRET
          FLEET_WORKSTATIONS_ENROLL_SECRET: op://GitHub/FLEET_WORKSTATIONS_ENROLL_SECRET
          FLEET_MOBILE_DEVICES_ENROLL_SECRET: op://GitHub/FLEET_MOBILE_DEVICES_ENROLL_SECRET
          FLEET_SECRET_SSH_USER: op://GitHub/FLEET_SECRET_SSH_USER
          FLEET_SECRET_SSH_PUBLIC_KEY: op://GitHub/FLEET_SECRET_SSH_PUBLIC_KEY
          
      - name: Checkout GitOps repository
        uses: actions/checkout@v4

      - name: Apply latest configuration to Fleet
        uses: ./.github/gitops-action
        with:
          # Run GitOps in dry-run mode for pull requests.
          dry-run-only: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        # Add FLEET_URL and FLEET_API_TOKEN to the repository secrets.
        # In addition, specify or add secrets for all the environment variables that are mentioned in the global/team YAML files.
        env:
          FLEET_URL: ${{ steps.op-secrets.outputs.FLEET_URL }}
          FLEET_API_TOKEN: ${{ steps.op-secrets.outputs.FLEET_API_TOKEN }}
          GLOBAL_ENROLL_SECRET: ${{ ssteps.op-secrets.outputs.GLOBAL_ENROLL_SECRET }}
          SSO_METADATA_URL: ${{ steps.op-secrets.outputs.SSO_METADATA_URL }}
          FLEET_SERVERS_ENROLL_SECRET: ${{ steps.op-secrets.outputs.FLEET_SERVERS_ENROLL_SECRET }}
          FLEET_WORKSTATIONS_ENROLL_SECRET: ${{ steps.op-secrets.outputs.FLEET_WORKSTATIONS_ENROLL_SECRET }}
          FLEET_MOBILE_DEVICES_ENROLL_SECRET: ${{ steps.op-secrets.outputs.FLEET_MOBILE_DEVICES_ENROLL_SECRET }}
          FLEET_SECRET_SSH_USER: ${{ steps.op-secrets.outputs.FLEET_SECRET_SSH_USER }}
          FLEET_SECRET_SSH_PUBLIC_KEY: ${{ steps.op-secrets.outputs.FLEET_SECRET_SSH_PUBLIC_KEY }}
