name: 'Apply latest configuration to Fleet'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # allows manual triggering
  schedule:
  - cron: '0 6 * * *' # Nightly 6AM UTC

# Prevent concurrent runs of this workflow.
concurrency:
  # unique per event + ref so runs from other branches/PRs don’t block each other
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  # cancel older runs on the same PR/branch so only the latest commit’s check remains
  cancel-in-progress: true

defaults:
  run:
    shell: bash

# Limit permissions of GITHUB_TOKEN.
permissions:
  contents: read

jobs:
  fleet-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4

      - name: Apply latest configuration to Fleet
        uses: ./.github/gitops-action
        with:
          # Run GitOps in dry-run mode for pull requests.
          dry-run-only: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        # Add FLEET_URL and FLEET_API_TOKEN to the repository secrets.
        # In addition, specify or add secrets for all the environment variables that are mentioned in the global/team YAML files.
        env:
          FLEET_URL: ${{ secrets.FLEET_URL }}
          FLEET_API_TOKEN: ${{ secrets.FLEET_API_TOKEN }}
          GLOBAL_ENROLL_SECRET: ${{ secrets.GLOBAL_ENROLL_SECRET }}
          GOOGLE_SSO_METADATA: ${{ secrets.GOOGLE_SSO_METADATA }}
          FLEET_SERVERS_ENROLL_SECRET: ${{ secrets.FLEET_SERVERS_ENROLL_SECRET }}
          FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET: ${{ secrets.FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET }}
          FLEET_WORKSTATIONS_ENROLL_SECRET: ${{ secrets.FLEET_WORKSTATIONS_ENROLL_SECRET }}
